#!/usr/bin/env ruby
# Usage: git cdbr
#
# from develop, cleans development branches that were merged already
def development_branches
  raw_branches = `git branch --merged`.split("\n")
                                      .map(&:strip)
                                      .reject { |e| e.match(/\s?master/) }
  raw_branches[1, raw_branches.length]
end

def current_branch
  `git rev-parse --abbrev-ref HEAD`.chomp
end

def in_develop?
  current_branch == 'develop'
end

def execute_in_develop
  if in_develop?
    yield
  else
    system('git checkout develop')
    yield
    system('git checkout -')
  end
end

def clean_development_branches
  execute_in_develop do
    development_branches.each do |branch|
      puts "removing #{branch}"
      system("git branch -d #{branch}")
    end
  end
end

clean_development_branches
