#!/usr/bin/env ruby
# Usage: git lb
#
# checks the current branch name and logs the differences with the parent

def get_current_branch
  `git rev-parse --abbrev-ref HEAD`.chomp
end

def log_in_relation_to_base_branch
  # develop (older branch) .. #(newer branch)
  system("git log --format='- [%h] %s%n%w(80,2,2)%b' develop..#{get_current_branch}")
end

log_in_relation_to_base_branch
