#!/usr/bin/env ruby
# Usage: git cdbr
#
# from master, cleans development branches that were merged already
def development_branches
  `git branch --merged`
    .split("\n")
    .map(&:strip)
    .reject { |e| e.match(/\s?master/) }
end

def current_branch
  `git rev-parse --abbrev-ref HEAD`.chomp
end

def in_master?
  current_branch == 'master'
end

def execute_in_master
  if in_master?
    yield
  else
    system('git checkout master')
    yield
    system('git checkout -')
  end
end

def clean_development_branches
  execute_in_master do
    development_branches.each do |branch|
      puts "removing #{branch}"
      system("git branch -d #{branch}")
    end
  end
end

clean_development_branches
